var isSplash=!0;$(document).ready(function(){0==location.hash.length&&"#!/undefined"==location.hash&&(location.hash="#!/");$("ul#menu").superfish({delay:800,animation:{height:"show"},speed:600,autoArrows:!1,dropShadows:!1,onInit:function(){$("#menu > li > a").each(function(){var a=$(this).find(".mText").text();$(this).append("<div class='menuTextOver'>"+a+"</div>")})}})});
$(window).load(function(){function a(){var a=$(window).height();a>c+40?(m_top=~~(a-c)/2,h_new=a):(m_top=20,h_new=c+40);$(".center").stop().animate({marginTop:m_top},800,"easeOutExpo")}$(".closeButton").hoverSprite({onLoadWebSite:!0});$(".followHolder > ul > li > a").hoverSprite({onLoadWebSite:!0});$(".women_slider").gallerySplash();homepage=$("#homepage");$(".pic").fancybox({titlePosition:"inside",overlayColor:"#000"});$(".gallScroll .overview").each(function(){var a=$("li",this).outerWidth(!0)*($("li",
this).length-1)+$("li:last",this).outerWidth();$(this).css({width:a})});$(".gallScroll").tinyscrollbar({axis:"x",sizethumb:"70",size:"700"});var b=GetWidth();"yes"==responsiveJS&&(959<b&&$(".gallScroll").tinyscrollbar({axis:"x",sizethumb:"70",size:"700"}),959>b&&767<b&&$(".gallScroll").tinyscrollbar({axis:"x",sizethumb:"70",size:"504"}),768>b&&479<b&&$(".gallScroll").tinyscrollbar({axis:"x",sizethumb:"70",size:"456"}),480>b&&$(".gallScroll").tinyscrollbar({axis:"x",sizethumb:"70",size:"316"}));$(".styleswitch").bind("click",
function(){$.stylesheetSwitch(this.getAttribute("rel"));return false});$(".btn1").toggle(function(){$(".switchHold").stop(true).animate({top:"0px"},300,"easeOutCubic");$(this).css({backgroundPosition:"0 100%"})},function(){$(".switchHold").stop(true).animate({top:"-58px"},300,"easeOutCubic");$(this).css({backgroundPosition:"0 0%"})});$(".zoomSp").fadeTo(500,0);$(".zoomSp").hover(function(){$(this).stop().fadeTo(500,0.5)},function(){$(this).stop().fadeTo(500,0)});var d=$("#menu >li");(function(){d.each(function(a){_delay=
a*100+500})})();$(".menu > ul >li");$("#content");b=$(".menu");$("#content").tabs({preFu:function(a){a.li.css({height:"0px",display:"none"});homepage.css({height:"0px",display:"none"})},actFu:function(a){a.n==-1?homepage.css({display:"block",height:"auto",top:"-2000px"}).stop().delay(400).animate({top:"0px"},600,"easeOutCubic"):homepage.stop().animate({display:"none",height:"0px",top:"400px"},400,"easeInCubic",function(){homepage.css({display:"none"})});if(a.curr){a.curr.css({display:"block",height:"auto",
top:"-2000px"}).stop().delay(400).animate({top:"0px"},600,"easeOutCubic");if(a.n==0&&(a.pren>0||a.pren==void 0))isSplash=true;if((a.pren==0||a.pren==void 0)&&a.n>0)isSplash=false}a.prev&&a.prev.stop().animate({height:"0px",top:"400px"},400,"easeInCubic",function(){a.prev.css({display:"none"})})}});b.navs({useHash:!0,defHash:"#!/",hoverIn:function(a){$(".mText",a).stop(true).animate({top:"50px"},500,"easeOutExpo");$(".menuTextOver",a).stop(true).animate({top:"0px"},500,"easeOutExpo")},hoverOut:function(a){if(!a.hasClass("with_ul")||
!a.hasClass("sfHover")){$(".mText",a).stop(true).animate({top:"0px"},500,"easeOutExpo");$(".menuTextOver",a).stop(true).animate({top:"-50px"},500,"easeOutExpo")}}}).navs(function(a){$("#content").tabs(a)});var c=900;a();$(window).resize(function(){a()});$(".icon1, .icon2, .icon3").sprites({method:"simple",duration:400,easing:"easeOutQuint",hover:!0})});
$(document).ready(function(){$(".btn-slide").click(function(){$("#panel").slideToggle("slow");$(this).toggleClass("active");return!1});$(".gallery .columnBox").live({mouseenter:function(){var a=$(this).find("a").children("img"),b=$(this).find(".overlay");a.stop().animate({opacity:0.8});b.css("left","-500px");overlayPos=a.width()/2-(b.width()/2-8);b.stop().animate({left:overlayPos})},mouseleave:function(){var a=$(this).find("a").children("img"),b=$(this).find(".overlay");a.stop().animate({opacity:1});
b.stop().animate({left:500})}})});$(document).ready(function(){$(".col305 .blogTemplateImg").live({mouseenter:function(){var a=$(this).find("a").children("img"),b=$(this).find(".overlay");a.stop().animate({opacity:0.8});b.css("left","-500px");overlayPos=a.width()/2-(b.width()/2-8);b.stop().animate({left:overlayPos})},mouseleave:function(){var a=$(this).find("a").children("img"),b=$(this).find(".overlay");a.stop().animate({opacity:1});b.stop().animate({left:500})}})});
window.onresize=function(){var a=GetWidth();"yes"==responsiveJS&&(959<a&&$(".gallScroll").tinyscrollbar({axis:"x",sizethumb:"70",size:"700"}),959>a&&767<a&&$(".gallScroll").tinyscrollbar({axis:"x",sizethumb:"70",size:"504"}),768>a&&479<a&&$(".gallScroll").tinyscrollbar({axis:"x",sizethumb:"70",size:"456"}),480>a&&$(".gallScroll").tinyscrollbar({axis:"x",sizethumb:"70",size:"316"}))};
function GetWidth(){var a=0;self.innerHeight?a=self.innerWidth:document.documentElement&&document.documentElement.clientHeight?a=document.documentElement.clientWidth:document.body&&(a=document.body.clientWidth);return a}
$(document).ready(function(){jQuery(".shortcode-toggle").length&&jQuery(".shortcode-toggle").each(function(){var a=jQuery(this);a.closedText=a.find('input[name="title_closed"]').attr("value");a.openText=a.find('input[name="title_open"]').attr("value");a.find('input[name="title_closed"]').remove();a.find('input[name="title_open"]').remove();a.find("h4.toggle-trigger a").click(function(){a.find(".toggle-content").animate({opacity:"toggle",height:"toggle"},300);a.toggleClass("open").toggleClass("closed");
a.hasClass("open")&&jQuery(this).text(a.openText);a.hasClass("closed")&&jQuery(this).text(a.closedText);return!1})})});
$(function(){$(".slides").slides({effect:"fade",fadeSpeed:1E3,play:6E3,pause:6E3,autoHeight:!0,generateNextPrev:!0,generatePagination:!1,crossfade:!0,hoverPause:!0,animationStart:function(a){$(".caption").animate({opacity:0}).css({display:"none"});window.console&&console.log&&console.log("animationStart on slide: ",a)},animationComplete:function(a){$(".caption").animate({opacity:1}).css({display:"block"});window.console&&console.log&&console.log("animationComplete on slide: ",a)},slidesLoaded:function(){$(".caption").animate({opacity:1}).css({display:"block"})}})});
$(function(){$("#slides").slides({effect:"fade",fadeSpeed:1E3,play:6E3,pause:6E3,autoHeight:!0,generateNextPrev:!0,generatePagination:!1,crossfade:!0,hoverPause:!0,animationStart:function(a){$(".caption").animate({opacity:0}).css({display:"none"});window.console&&console.log&&console.log("animationStart on slide: ",a)},animationComplete:function(a){$(".caption").animate({opacity:1}).css({display:"block"});window.console&&console.log&&console.log("animationComplete on slide: ",a)},slidesLoaded:function(){$(".caption").animate({opacity:1}).css({display:"block"})}})});
$(document).ready(function(){$("a.portfPic").fancybox({overlayColor:"#1c1c1c",transitionIn:"elastic",transitionOut:"elastic",speedIn:500,speedOut:300});$(".imgList3 li a.iframe").fancybox({width:"70%",height:"70%",type:"iframe",transitionIn:"elastic",transitionOut:"elastic",speedIn:500,speedOut:300});$("#fancybox-overlay").css({minWidth:minW,minHeight:minH})});