(function(b){b.fn.sprites=function(e){this.each(function(){var f=b(this),g=f.data("sprites"),a={ready:!1,method:"corners",pasta:"<div></div>",hover:!1,altEventIn:"hoverin",altEventOut:"hoverout",duration:300,easing:"linear",crossFade:!0,processFu:function(){({vStretch:function(){a.layers=a.layers||{};a.corners=a.corners||{};a.tails=a.tails||{};a.layers.t=a.corners.t=a.etal.clone().css({top:0,backgroundPosition:"0 0"});a.layers.b=a.corners.b=a.etal.clone().css({bottom:0,backgroundPosition:"-"+a.width/
3+"px 0"});a.layers.c=a.tails.c=a.etal.clone().css({top:a.height,bottom:a.height,backgroundPosition:"-"+2*(a.width/3)+"px 0",backgroundRepeat:"repeat-y"});b.each(a.layers,function(b,c){c.css({position:"absolute",backgroundImage:a.url,zIndex:-1,left:0,width:a.width/3}).appendTo(a.me)});b.each(a.corners,function(b,c){c.css({height:a.height})});a.me.css({background:"none"})},gStretch:function(){var d=a.hover?a.height/6:a.height/3;a.layers=a.layers||{};a.corners=a.corners||{};a.tails=a.tails||{};a.hovers=
a.hovers||{};a.layers.l=a.corners.l=a.etal.clone().css({left:0,backgroundPosition:"0 0"});a.layers.r=a.corners.r=a.etal.clone().css({right:0,backgroundPosition:"0 -"+d+"px"});a.layers.c=a.tails.c=a.etal.clone().css({right:a.width,left:a.width,backgroundPosition:"0 -"+2*d+"px"});b.each(a.layers,function(b,e){e.css({position:"absolute",backgroundImage:a.url,zIndex:-1,top:0,height:d}).appendTo(a.me)});b.each(a.corners,function(b,d){d.css({width:a.width})});a.hover&&(b.each(a.layers,function(c,d){a.hovers[c]=
d.clone().appendTo(a.me).hide();b.browser.msie&&9>b.browser.version||a.hovers[c].css({opacity:0})}),a.hovers.l.css({backgroundPosition:"0 -"+3*d+"px"}),a.hovers.r.css({backgroundPosition:"0 -"+4*d+"px"}),a.hovers.c.css({backgroundPosition:"0 -"+5*d+"px"}));a.me.css({background:"none"})},simple:function(){a.layers=a.layers||{};a.hovers=a.hovers||{};a.layers.bg=a.etal.clone().css({left:0,top:0,zIndex:-1,width:a.width,height:a.height/2,backgroundImage:a.url,backgroundRepeat:"no-repeat",backgroundPosition:"0 0"}).appendTo(a.me);
a.hovers.bg=a.etal.clone().css({left:0,top:0,zIndex:-1,width:a.width,height:a.height/2,backgroundImage:a.url,backgroundRepeat:"no-repeat",backgroundPosition:"0 -"+a.height/2+"px"}).appendTo(a.me);b.browser.msie&&9>b.browser.version?a.hovers.bg.hide():a.hovers.bg.css({opacity:0});a.me.css({background:"none"})},corners:function(){a.layers=a.layers||{};a.corners=a.corners||{};a.tails=a.tails||{};a.layers["l-t"]=a.corners["l-t"]=a.etal.clone().css({left:0,top:0,backgroundPosition:"0 0"});a.layers["r-t"]=
a.corners["r-t"]=a.etal.clone().css({right:0,top:0,backgroundPosition:"-"+a.width/4+"px 0"});a.layers["l-b"]=a.corners["l-b"]=a.etal.clone().css({left:0,bottom:0,backgroundPosition:"0 -"+a.height/4+"px"});a.layers["r-b"]=a.corners["r-b"]=a.etal.clone().css({right:0,bottom:0,backgroundPosition:"-"+a.width/4+"px -"+a.height/4+"px"});a.layers["t-l"]=a.etal.clone().css({left:0,top:a.height/4,bottom:a.height/4,width:a.width/4,backgroundPosition:"-"+a.width/2+"px 0"});a.layers["t-l-c"]=a.layers["t-l"].clone().css({backgroundPosition:"-"+
a.width/2+"px -"+a.height/2+"px"});a.layers["t-r"]=a.etal.clone().css({right:0,top:a.height/4,bottom:a.height/4,width:a.width/4,backgroundPosition:"-"+(a.width/2+a.width/4)+"px 0"});a.layers["t-r-c"]=a.layers["t-r"].clone().css({backgroundPosition:"-"+(a.width/2+a.width/4)+"px -"+a.height/2+"px"});a.layers["t-t"]=a.etal.clone().css({top:0,height:a.height/4,left:a.width/4,right:a.width/4,backgroundPosition:"0 -"+a.height/2+"px"});a.layers["t-t-c"]=a.layers["t-t"].clone().css({backgroundPosition:"-"+
a.width/2+"px -"+a.height/2+"px"});a.layers["t-b"]=a.etal.clone().css({bottom:0,height:a.height/4,left:a.width/4,right:a.width/4,backgroundPosition:"0 -"+(a.height/2+a.height/4)+"px"});a.layers["t-b-c"]=a.layers["t-b"].clone().css({backgroundPosition:"-"+a.width/2+"px -"+(a.height/2+a.height/4)+"px"});a.layers.bgc=a.etal.clone().css({left:a.width/4,right:a.width/4,top:a.height/4,bottom:a.height/4});b.each(a.layers,function(b,c){c.css({position:"absolute",backgroundImage:a.url,zIndex:-1}).appendTo(a.me)});
b.each(a.corners,function(b,c){c.css({width:a.width/4,height:a.height/4})});a.layers.bgc.css({background:a.me.css("backgroundColor")});a.me.css({background:"none"})}})[a.method]()},showHoverFu:function(){b.each(a.hovers,function(d,c){b.browser.msie&&9>b.browser.version?c.show():c.stop().show().animate({opacity:1},{duration:a.duration,easing:a.easing})});b.each(a.layers,function(d,c){b.browser.msie&&9>b.browser.version?c.hide():a.crossFade&&c.stop().show().animate({opacity:0},{duration:a.duration,
easing:a.easing,complete:function(){c.hide()}})})},hideHoverFu:function(){a.hovers&&b.each(a.hovers,function(d,c){b.browser.msie&&9>b.browser.version?c.hide():c.stop().show().animate({opacity:0},{duration:a.duration,easing:a.easing,complete:function(){c.hide()}})})&&b.each(a.layers,function(d,c){b.browser.msie&&9>b.browser.version?c.show():c.stop().show().animate({opacity:1},{duration:a.duration,easing:a.easing})})},hoverFu:function(){a.hover&&a.me.bind(!0===a.hover?"mouseenter":a.altEventIn,function(){a.showHoverFu();
a.hoverIn(a.me,a)}).bind(!0===a.hover?"mouseleave":a.altEventOut,function(){a.hideHoverFu();a.hoverOut(a.me,a)})},preFu:function(){var d=b('<img src="">').appendTo("body");a.url=f.css("backgroundImage");a.src=a.url.replace(/(^url\('?"?)|('?"?\)$)/g,"");"static"==a.me.css("position")&&a.me.css({position:"relative"});"inline"==a.me.css("display")&&a.me.css({display:"inline-block"});"auto"==a.me.css("zIndex")&&a.me.css({zIndex:1});a.etal=b(a.pasta).css({position:"absolute",zIndex:-1});a.hh=a.me.outerHeight();
a.hw=a.me.outerWidth();d.css({position:"absolute",left:"-999%",top:"-999%",display:"block"}).load(function(){setTimeout(function(){a.width=d.width();a.height=d.height();d.remove();a.processFu();a.ready=!0;a.lazyFu&&a.lazyFu()},1)}).attr({src:a.src});a.hover&&a.hoverFu()},init:function(){a.preFu()},controlFu:function(b){"hoverin"==b&&a.showHoverFu();"hoverout"==b&&a.hideHoverFu()},hoverIn:function(){},hoverOut:function(){}};g?a=g:f.data({sprites:a});"object"==typeof e&&b.extend(a,e);a.me||a.init(a.me=
f);"string"==typeof e&&(a.ready?a.controlFu(e):a.lazyFu=function(){a.controlFu(e);a.me.trigger("ready")})});return this}})(jQuery);